from snippets.mass_edits import mass_translate

REPLACE_MAP = {
    "Continue...": "Continuar...",
    "Do nothing.": "No hacer nada.",
    "Do something onboard the ship.": "Hacer algo abordo de la nave.",
    "...": "...",
    "Nevermind.": "No importa.",
    "An unvisited location.": "Una ubicación no visitada.",
    "Explored location. Nothing left of interest.": "Ubicación explorada. No hay nada más de interés.",
    "YOU SHOULD NEVER SEE THIS": "NUNCA DEBISTE HABER VISTO ESTO",
    "Use your blessing to avoid combat.": "Usar tu bendición para evitar combate.",
    "Decline.": "Declinar.",
    "Yes.": "Sí.",
    "Refuse.": "Negarse.",
    "No.": "No.",
    "You start calibrating the drone...": "Empiezas a calibrar el dron...",
    "You finish calibrating the drone successfully.": "Terminas de calibrar el dron exitosamente.",
    "Return to the toggle menu.": "Regresar al menú de alternaciones.",
    "Renegade Cruiser": "Crucero renegado",
    "Leave.": "Irse.",
    "Detach both modules.": "Desprender ambos módulos.",
    "Exit hyperspeed.": "Salida a hipervelocidad.",
    "You install the upgrade.": "Instalas la mejora.",
    "You start the process.": "Empiezas el proceso.",
    "You finish the process.": "Terminas el proceso.",
    "Your crew cannot be cloned on your ship as they are inside the cannon.": "Tu tripulante no puede ser clonado en tu nave, porque está dentro del cañón.",
    "You install the modification.": "Instalas la modificación.",
    "Are you sure? You will not be able to retrieve them without a Clone Bay, and all skills will be lost.": "¿Estás seguro? No serás capaz de recuperarle sin una sala de clonación y todas sus habilidades serán perdidas.",
    "Reset the cannon.": "Reiniciar el cañón.",
    "You reset the weapon.": "Reinicias el cañón.",
    "You finish resetting the weapon.": "Terminas de reiniciar el cañon.",
    "Your Morph transforms into a new shape.": "Tu Morph se transforma en una nueva forma.",
    "Projectile": "Proyectil",
    "(Clone Bay) Revive your crew.": "(Sala de clonación) Revivir a tu tripulante.",
    "Though your crew's memories have been almost completely erased, they remember enough to at least remain loyal to the Federation.": "Aunque las memorias de tu tripulante han sido casi completamente borradas, puede recordar lo suficiente para mantenerse leal a la Federación.",
    "Ignore them.": "Ignorarlos.",
    "Are you sure you want to change the drone's settings?": "¿Estás seguro de que quieres cambiar la configuración del dron?",
    "Reroute.": "Redirigirse.",
    "Accept their surrender.": "Aceptar su rendición.",
    "Nevermind, do something else.": "No importa, hacer algo más.",
    "Continue to the fight!": "¡Continuar con el combate!",
    "???": "¿¿¿???",
    "Sylvan": "Sylvan",
    "YOU SHOULD NEVER SEE THIS.": "NUNCA DEBISTE HABER VISTO ESTO",
    "No weapon has ever sparked a larger ethical controversy, but if it works it works.": "Ningún arma ha alguna vez iniciado mayor controversia ética, pero si funciona funciona.",
    "Accept.": "Aceptar.",
    "No thanks.": "No gracias.",
    "Contact Federation command.": "Contactar al mando de la Federación.",
    "Multiverse Renegade": "Renegado del Multiverso",
    "Attack!": "¡Atacar!",
    ".": ".",
    "Continue with the jump.": "Continuar con el salto.",
    "You prepare to jump to the new co-ordinates, and change your flight path accordingly.": "Te preparas para saltar a las nuevas coordenadas, y cambias tus planes de vuelo en consecuencia.",
    "You prepare to secure their cargo by force.": "Te preparas para asegurar su cargo por la fuerza.",
    "Agree.": "Aceptar.",
    "Hail them.": "Llamarlos.",
    "Avoid the ship.": "Evitar la nave.",
    "Your Morph transforms back to its original shape.": "Tu Morph se transforma de nuevo a su forma original.",
    "Go back.": "Retroceder.",
    "ESSENTIAL SYSTEMS": "SISTEMAS ESENCIALES",
    "AUXILIARY SYSTEMS": "SISTEMAS AUXILIARES",
    "(Cloaking) Cloak and try to escape.": "(Ocultación) Ocultarse e intentar escapar.",
    "(Adv. Engines) Try to escape the guard.": "(Motores Avanzados) Intentar escapar del guardia.",
    "Character Recruited": "Personaje Reclutable",
    "Explore.": "Explorar.",
    "(Adv. Piloting) Activate the auto-pilot to try and escape.": "(Pilotaje Avanzado) Activar el piloto automático para intentar escapar.",
    "Detach the modules.": "Desprender ambos módulos.",
    "DECKHANDS": "TRABAJADOR DE CUBIERTA",
    "Before you shop, you still have some time to do something else aboard the ship.": "Antes de comprar, aún tienes algo de tiempo para hacer algo más abordo de la nave.",
    "Success!": "¡Éxito!",
    "Loot Acquired": "Botín Adquirido",
    "Modular Laser": "Laser Modular",
    "Mod. Laser": "Laser Mod.",
    "Modular Ion": "Ion modular",
    "Mod. Ion": "Ion Mod.",
    "They stay outside your weapons range, and eventually jump away.": "Ellos se mantienen afuera del alcance de tus armas y eventualmente saltan a otra parte.",
    "DRONE": "DRON",
    "*%$##@*%!": "*%$##@%¡",
    "Servant": "Sirviente",
    "Demand the surrender of their goods.": "Demandar la entrega de sus bienes.",
    "WEAPONS OF THE DAY [33% OFF]": "ARMAS DEL DÍA [33% DE DESCUENTO]",
    "They look like they don't want to fight. They are trying to escape.": "Parece que ellos no quieren combatir. Están tratado de escapar.",
    "AUGMENTS OF THE DAY [33% OFF]": "AUMENTOS DEL DÍA [33% DE DESCUENTO]",
    "Chaotic Renegade Cruiser": "Crucero Renegado Caótico",
    "Special loot weapon. See tooltip in the inventory to check the improvements over the base version.": "Arma especial de botin. Mira el apartado de información en el inventario para comprobar las mejoras sobre la versión base.",
    "Your new crew materializes in the room.": "Tu nuevo tripulante se materializa en la sala.",
    "You power up the machine to max and watch as a rift opens, shaking the ship until suddenly it powers off, and a flashing green light followed by a string of coordinates signifies that it has worked.": "Pones la máquina al máximo de energía y miras como la grieta se abre, hace temblar la nave hasta que se apaga de la nada y una parpadeante luz verde seguida de unas coordenadas significa que ha funcionado.",
    "Do something else instead.": "Hacer algo más en vez.",
    "Renegade Defeated": "Renegado Derrotado",
    "Boon Received": "Bención Recibida",
    "Attack the guard.": "Atacar al guardia.",
    "Return.": "Regresar.",
    "DRONES OF THE DAY [33% OFF]": "DRON DEL DÍA [33% DE DESCUENTO]",
    "Modular Missile": "Misil Modular",
    "Mod. Missile": "Misil Mod.",
    "We can't help.": "No podemos ayudar.",
    "Install the External Augment internally.": "Instalar el Aumento Externo en el interior.",
    "You activate the combat augment.": "Activas el aumento de combate.",
    "The crew is dead, leaving you with the ship. Its cargo is yours for the taking. Aboard is the special tech you expected, which you bring back to your ship.": "La tripulación está muerta, dejandote con el control de la nave. Su carga es tuya ahora. Abordo está la tecnología especial que esperabas, la cual traes de vuelta a tu nave.",
    "Ignore the station.": "Ignorar la estación.",
    "(Jerry) \"Hello!\"": "(Jerry) \"¡Hola!\"",
    "Listen.": "Escuchar.",
    "Accept their offer.": "Aceptar su oferta.",
    "Ignore the ship.": "Ignorar la nave.",
    "Attack them.": "Atacarles.",
    "Close your eyes and relax...": "Cierras tus ojos y te relajas...",
    "Install the Firestarter Module.": "Instalar el Módulo Incendiario.",
    "Install the Hullbuster Module.": "Instalar el Módulo Revientacascos.",
    "Install the Power Module.": "Instalar el Módulo de Poder.",
    "Get to Sector 5 with the Type A to unlock this ship.": "Llega al Sector 5 con el Tipo A para desbloquear esta nave.",
    "(Adv. Engines) Try to escape the Elite.": "(Motores Avanzados) Intentar escapar del Elite.",
    "Obyn": "Obyn",
    "You decide not to do anything and prepare to fight.": "Decides no hacer nada y prepararte para el combate.",
    "Get to Sector 5 with the Type B or beat the game with the Type A to unlock this ship.": "Lega al Sector 5 con el Tipo B o gana el juego con el Tipo A para desbloquear esta nave.",
    "Modular Beam": "Rayo Modular",
    "Mod. Beam": "Rayo Mod.",
    "Leave them be.": "Dejarlos ser.",
    "Attack them!": "¡Atacarles!",
    "(Mind Control) Convince the guard to leave you alone.": "(Control Mental) Convencer al guardia para dejarte solo.",
    "Nevermind, let's fight!": "No importa, ¡a combatir!",
    "Approach.": "Acercarse.",
    "Accept the job.": "Aceptar el trabajo.",
    "The alarms buzz and an extra layer of security slams shut on the vault door. You quickly flee but the Zoltan reinforcements arrive just in time to fire a barrage of missiles straight through your defences before you can escape.": "La alarma suena y una capa extra de seguridad bloquea la puerta de la cámara. Huyes rápidamente, pero justo llegan los refuerzos Zoltan y empiezan a dispararte misiles antes de que puedas escapar.",
    "L-9678": "L-9678",
    "Contact the civilian ship.": "Contactar la nave civil.",
    "Install the Anti-Bio Module.": "Instalar el Módulo Anti-biológico.",
    "Install the Cooldown Module.": "Instalar el Módulo de Recarga.",
    "Install the Neural Module.": "Instalar el Módulo Neurológico.",
    "Prepare to fight!": "¡Prepararte para el combate!",
    "Attack the outpost!": "¡Atacar la estación!",
    "(Magnet Arm) Salvage the wreck further.": "(Brazo Magnetico) Obtener todavía más del naufragio.",
    "You now have some time to do something on the ship.": "Ahora tienes algo de tiempo para hacer algo en la nave.",
    "\"Another day, another profit for both of ussss, eh ssstranger?\"": "\"Otro día, otra oportunidad para ambosss, eh desssconocido?\"",
    "You cannot install this lab modification, as you still have the external version.": "No puedes instalar la modificación de laboratorio, porque aún tienes la versión externa.",
    "Artillery": "Artillería",
    "Anointed": "La Elegida",
    "You prepare for combat.": "Te preparas para el combate.",
    "Ignore the guard.": "Ignoras al guardia.",
    "That's enough for now.": "Eso es suficiente por ahora.",
    "Install the Accuracy Module.": "Instalar el Módulo de Precisión.",
    "Currently Installed: None": "Actualmente Instalado: Nada",
    "PHEROMONE": "FEROMONA",
    "Grant Received": "Bendición Recivida",
    "Blessing Received": "Bendición Recivida",
    "Pirate Fighter": "Combatiente Pirata",
    "Task Marker": "Marcador de Tareas",
    "Obsidian Armor": "Blindaje de Obsidiana",
    "Leave them alone.": "Dejalos en paz.",
    "Attack the ship.": "Atacar la nave.",
    "Dock.": "Atracar.",
    "\"Task accepted. Transferring coordinates to next sector. Do not disappoint me.\"": "\"Tarea aceptada. Transfiriendo coordenadas para el siguiente sector. No me decepciones.\"",
    "From out of the tunnel comes a massive cruiser vessel, of unknown alien design! At once, a strange pattern appears on your computer... its frequency matches the signal from that beacon you had activated earlier!": "¡Del tunel sale un crucero masivo de un diseño alienígena desconocido! Al mismo tiempo, un extraño patrón aparece en tu computadora... ¡Sus frecuencias son iguales a la señal de la baliza que activaste antes!",
    "You arm the weapons and engage the station!": "¡Enciendes tus armas y te enfrentas a la estación!",
    "You activate the payload and launch it from the vessel.": "Activas la carga explosiva y la lanzas desde la nave.",
    "Set the drone to Boarding Mode.": "Poner el dron en Modo de Abordaje.",
    "Pirate Scout": "Explorador Pirata",
    "Traveling Merchant": "Mercader Viajero",
    "Multiverse Flagship": "Nave Insignia del Multiverso",
    "Pay.": "Pagar.",
    "You give the weapon to the engineer, allowing him to work on it.": "Le entregas la arma al ingeniero, permitiendole trabajar en ella.",
    "After a short time, your weapon is returned to you, clad with an optimization.": "Después de un corto tiempo, tu arma se te es devuelta, llena de optimizaciones.",
    "Contact the guard.": "Contactar al guardia.",
    "Install the Lockdown Module.": "Instalar el Módulo Bloqueador.",
    "You must have the lab upgrade for this modification.": "Debes de tener la mejora de laboratorio para esta modificación.",
    "You begin the upgrade...": "Empiezas con la mejora...",
    "Power rerouted to surge control. Proceeding to combat.": "Energía redigida al control de sobrecargas",
    "Your Power Surge will occur after this countdown.": "Tu Sobrecarga de Energía ocurrirá después de esta cuenta regresiva.",
    "BOMB": "BOMB",
    "Pirate Outrider": "Escolta Pirata",
    "Investigate.": "Investigar.",
    "Request supplies.": "Pedir suministros.",
    "Contact the refugee ship.": "Contactar con la nave de refugiados.",
    "See what they're selling.": "Mirar que están vendiendo.",
    "Install the Pierce Module.": "Instalar el Módulo Perforador",
    "What upgrade do you want to install?": "¿Qué mejora deseas instalar?",
    "Your Malform transforms back to its original shape.": "Tu Malform se transforma de vuelta a su forma original.",
    "Attack, we can steal their Mine Launcher tech!": "Atacar, ¡podemos robar su tecnología de Lanzador de Minas!",
    "You've taken the risky choice of fighting the ship. Hopefully, you can protect yourself from their salvo long enough.": "Has tomado la riesgosa desición de combatir esta nave. Con suerte, puedes protegerte de su carga lo suficiente.",
    "Avoid the Trapper.": "Evitar el Trampero de Minas.",
    "Messing with a Trapper is a bad idea.": "Meterse con un Trampero de Minas es una mala idea.",
    "Human": "Humano",
    "Thing": "Cosa",
    "Contact the Engi.": "Contactar con los Engis.",
    "Sure.": "Claro.",
    "The ship breaks apart and you quickly salvage what you can.": "La nave se rompe en pedazos y tú rápidamente recoges lo que puedes.",
    "Salvage the ruins.": "Saqueas las ruinas.",
    "You rig the ammunition and set a trap for the Rebels. It's definitely illegal to do, but you'll be gone before it matters.": "Modificaste la munición y dejaste una trampa para los rebeldes. Es algo definitivamente ilegal, pero te habrás ido antes de que importe.",
    "Pirate Transport": "Transporte Pirata",
    "Mascot": "Mascota",
    "Merchant": "Mercader",
    "Awesome Laser": "Laser Increíble",
    "Respond.": "Responder.",
    "Attack the station!": "¡Atacar la estación!",
    "Surrender is not an option.": "La rendición no es una opción.",
    "\"A good choice. May it serve you well in your travels!\"": "\"Una buena decisión. ¡Puede que te sirva bastante en tus viajes!",
    "Jerry": "Jerry",
    "We have to go.": "Tenemos que irnos.",
    "I should go.": "Tengo que irme.",
    "Charlie": "Charlie",
    "The haunted vessel has been eliminated. Another to check off the list this time. That is, assuming they don't pop up again from across the Multiverse looking for revenge.": "La nave embrujada ha sido eliminada. Otra cosa tachada de la lista. Eso sí, asumiento de que no vuelvan por venganza desde el Multiverso.",
    "You mute the ship and prepare for combat.": "Silencias la nave y te preparas para el combate.",
    "You await your reward, but the machine buzzes and an X flashes on the screen. Better luck next time...": "Esperas tu premio, pero la máquina solo zumba y una X parpadea en la pantalla. Mejor suerte para la próxima...",
    "Gamble again.": "Apostar de nuevo.",
    "System disabled successfully.": "Sistema exitosamente desactivado",
    "Pirate Bomber": "Bombardero Pirata",
    "Tiiikaka Transport": "Transporte Tiiikaka",
    "Max Health is increased to 110": "Vida máxima aumentada a 110",
    "Ignore the planet.": "Ignorar el plantea.",
    "Finish them off.": "Acabar con ellos.",
    "Scrap the ship.": "Chatarrear la nave.",
    "Continue.": "Continar.",
    "We aren't interested.": "No estamos interesados.",
    "Okay.": "Okay.",
    "It seems your track record has caught up to you. The guard's crew have heard enough of the crimes you've been committing, and they don't intend to let you into the sector!": "Parece que tu reputación te ha precedido. La tripulación de la nave guardian ha escuchado lo suficiente sobre los crímenes que has cometido, ¡y parece que ellos no te van a dejar entrar a este sector!.",
    "You rush to defensive positions as the guard approaches menacingly.": "Te apresuras a tomar posiciones defensivas mientras el guardia se acerca amenazantemente.",
    "Here we go again.": "Aquí vamos de nuevo.",
    "(Powerful Beam) Show the Beam to Leah.": "(Rayo Poderoso) Enseñarle el Rayo a Leah.",
    "Whatever the ruins have to offer isn't worth the effort.": "Lo que sea que las ruinas contengan no vale el esfuerzo.",
    "Ignore the merchant.": "Ignorar al mercader.",
    "Yes": "Sí",
    "Set the drone to Defensive Mode.": "Poner el dron el Modo Defensivo.",
    "Free Mantis Elder": "Mantis Libre Anciano",
    "Morph": "Morph",
    "Active Ability: Deploys a Breach, Lockdown, and Ion Bomb at the same time": "Habilidad Activable: Usa una Bomba de Brecha, de Bloqueo y de Ion al mismo tiempo",
    "Recon Drone": "Dron de Reconocimiento",
    "Battle Drone": "Dron de Combate",
    "Ignore the ships.": "Ignorar las naves.",
    "You were asked to escort an unprepared vessel to these coordinates.": "Se te ha sido encomendado escortar una nave no preparada a estas coordenadas.",
    "Wait.": "Esperar.",
    "More boarding pods are approaching!": "¡Más capsulas de abordaje se están acercando!",
    "What?": "¿Qué?",
    "Your crew cannot be cloned, as you just sold them.": "Tu tripulante no puede ser clonado, porque lo acabas de vender.",
    "With the crew dead you quickly salvage what you can.": "Con la tripulación muerta, rapidamente saqueas lo que puedes.",
    "Contact the Monks.": "Contactar a los Monjes.",
    "The slave ship is destroyed. They won't continue their evil trade, but many lives were probably lost on that ship.": "La nave esclavista ha sido destruida. Ellos no van a continuar con su vil comercio, pero muchas vidas fueron probablemente perdidas en dicha nave.",
    "Demand supplies.": "Demandar suministros.",
    "Change your mind and leave the guard alone.": "Cambiar de opinión y dejar al guardia en paz.",
    "You apologize and end comms. The guard makes no attempts to communicate further.": "Te disculpas y cortas comunicaciones. El guardia no hace ningún otro intento para comunicarse.",
    "This is the location of the Traveling Merchant.": "Esta es la ubicación del Mercader Viajero.",
    "Er... sorry?": "¿Ehhh... disculpa?",
    "Buy the pen.": "Comprar el lapicero.",
    "Rescue the store.": "Rescatar la tienda.",
    "Shop.": "Comprar.",
    "Success, time for battle!": "Éxito, ¡tiempo para el combate!",
    "Buy the cargo.": "Comprar la carga.",
    "The transaction is done. With the looks of it, this piece of equipment might prove useful.": "La transacción está hecha. Por como se ve, está pieza de equipamiento puede ser útil.",
    "Refuse and attack the transport.": "Negarse y atacar el transporte.",
    "The transport captain shrugs and continues on their way.": "El capitan del transporte encoge los hombros y continua su camino.",
    "Leah": "Leah"
}

mass_translate('locale/**/es.po', REPLACE_MAP, overwrite=True)
