from snippets.mass_edits import mass_translate

REPLACE_MAP = {
    "Continue...": "Kontynuuj",
    "Do nothing.": "Nie rób nic",
    "...": "...",
    "Do something onboard the ship.": "Zrób coś na pokładzie statku",
    "Nevermind.": "Nieważne",
    "An unvisited location.": "Lokalizacja nieodwiedzona",
    "Explored location. Nothing left of interest.": "Miejsce odwiedzone. Nie pozostało nic interesującego.",
    "Use your blessing to avoid combat.": "Użyj swojego błogosławieństwa by uniknać walki",
    "YOU SHOULD NEVER SEE THIS": "NIGDY NIE POWINIENEŚ TEGO ZOBACZYĆ",
    "Yes.": "Tak",
    "No.": "Nie",
    "Decline.": "Odmowa",
    "Detach both modules.": "Odczep oba moduły",
    "Refuse.": "Odmowa",
    "You start calibrating the drone...": "Zaczynasz kalibrować drona...",
    "You finish calibrating the drone successfully.": "Udało się poprawnie skalibrować drona",
    "Renegade Cruiser": "Krążownik Renegatów",
    "Return to the toggle menu.": "Powrót do menu przełączającego",
    "Leave.": "Odejdź/wyjdź",
    "Your Morph transforms into a new shape.": "Twoj Morph przybiera nową formę",
    "You start the process.": "Zaczynasz proces",
    "You finish the process.": "Kończysz proces",
    "Your crew cannot be cloned on your ship as they are inside the cannon.": "Twoja załoga nie może być sklonowana kiedy znajduje się wewnątrz działa",
    "Reset the cannon.": "Resetowanie działa",
    "You reset the weapon.": "Resetujesz broń",
    "Projectile": "Pocisk",
    "You install the upgrade.": "Instalujesz ulepszenie",
    "Exit hyperspeed.": "Opuszczasz predkość nadświetlną",
    "Continue with the jump.": "Przygotuj sie do skoku",
    "You prepare to jump to the new co-ordinates, and change your flight path accordingly.": "Przygotowujesz się do skoku na nowe współrzędne i odpowiednio zmieniasz trasę lotu.",
    "You install the modification.": "Instalujesz modyfikację",
    "Are you sure you want to change the drone's settings?": "Jesteś pewien że chcesz zmienić ustawienia dronów?",
    "Accept their surrender.": "Zaakceptuj ich poddanie się",
    "Ignore them.": "Ignoruj ich",
    "???": "???",
    "Reroute.": "Zmiana trasy",
    "Nevermind, do something else.": "Nieważne, zrób coś innego",
    "Accept.": "Zgoda",
    "Continue to the fight!": "Do walki!",
    "Sylvan": "Sylvan", 
    "YOU SHOULD NEVER SEE THIS.": "NIGDY NIE POWINIENEŚ TEGO ZOBACZYĆ",
    "Drone": "Dron",
    "Contact Federation command.": "Skontaktuj się z dowództwem Federacji",
    "Detach the modules.": "Odczep moduły",
    "No thanks.": "Nie dzięki",
    "Attack!": "Atakuj!",
    "Multiverse Renegade": "Wieloświatowy Renegat",
    ".": ".",
    "No weapon has ever sparked a larger ethical controversy, but if it works it works.": "Żadna broń nie wywołała nigdy większych kontrowersji etycznych, ale jeśli działa, to działa.",
    "Agree.": "Zgoda",
    "You prepare to secure their cargo by force.": "Przygotowujesz się by zabezpieczyć ładunek za pomocą siły",
    "Avoid the ship.": "Uniknij statku",
    "Hail them.": "Powitaj ich",
    "Your Morph transforms back to its original shape.": "Twój Morph zmienia swoją formę na oryginalną",
    "ESSENTIAL SYSTEMS": "SYSTEMY PODSTAWOWE",
    "AUXILIARY SYSTEMS": "SYSTEMY POMOCNICZE",
    "Go back.": "Powrót",
    "*%$##@*%!": "%$##@*%",
    "(Cloaking) Cloak and try to escape.": "(Maskowanie) Ukryj się i spróbuj uciec.",
    "(Adv. Engines) Try to escape the guard.": "(Zaawansowane silniki) Spróbuj uciec strażnikowi.",
    "Character Recruited": "Postać zwerbowana",
    "DECKHANDS": "Załoganci",
    "Chaotic Renegade Cruiser": "Chaotyczny Krążownik Renegatów",
    "Explore.": "Eksploruj",
    "Before you shop, you still have some time to do something else aboard the ship.": "Przed zakupami masz jeszcze trochę czasu, aby zrobić coś innego na pokładzie statku.",
    "(Adv. Piloting) Activate the auto-pilot to try and escape.": "(Zaawansowane pilotowanie) Włącz autopilota, aby spróbować uciec.",
    "You power up the machine to max and watch as a rift opens, shaking the ship until suddenly it powers off, and a flashing green light followed by a string of coordinates signifies that it has worked.": "Włączasz urządzenie na pełną moc i obserwujesz, jak otwiera się szczelina. Statkiem wstrząsa, aż nagle urządzenie się wyłącza. Migające zielone światło, po którym pojawia się ciąg współrzędnych, oznacza, że zadziałało.",
    "Renegade Defeated": "Renegat pokonany",
    "Special loot weapon. See tooltip in the inventory to check the improvements over the base version.": "Specjalna broń zdobyczna. Sprawdź opis w ekwipunku, aby zapoznać się z ulepszeniami w stosunku do wersji podstawowej.",
    "Install the Firestarter Module.": "Zainstaluj moduł Ogniostarter",
    "Install the Hullbuster Module.": "Zainstaluj moduł Kadłubo-niszczący",
    "Install the Power Module.": "Zainstaluj moduł Mocy",
    "Loot Acquired": "Zdobyty łup",
    "DRONE": "DRONY",
    "Success!": "Sukces!",
    "They stay outside your weapons range, and eventually jump away.": "Pozostają poza zasięgiem twojej broni i ostatecznie odskakują.",
    "Modular Laser": "Laser Modułowy",
    "Mod. Laser": "Laser Mod",
    "Modular Ion": "Jon Modułowy",
    "Mod. Ion": "Jon Mod",
    "Attack them.": "Zaatakuj ich",
    "Demand the surrender of their goods.": "Zażądaj oddania ich ładunku",
    "WEAPONS OF THE DAY [33% OFF]": "PRZECENA BRONI [33% MNIEJ]",
    "Servant": "Sługa",
    "Install the Anti-Bio Module.": "Zainstaluj moduł Anty-Bio",
    "Install the Cooldown Module.": "Zainstaluj moduł Chłodzenie",
    "Install the Neural Module.": "Zainstaluj moduł Neuronowy",
    "They look like they don't want to fight. They are trying to escape.": "Wyglądają, jakby nie chcieli walczyć. Próbują uciec.",
    "AUGMENTS OF THE DAY [33% OFF]": "PRZECENA ULEPSZEŃ [33% MNIEJ]",
    "Attack the guard.": "Zaatakuj strażnika",
    "Install the Accuracy Module.": "Zainstaluj moduł Celności",
    "Install the External Augment internally.": "Zainstaluj zewnętrzne rozszerzenie bezpośrednio.",
    "Your new crew materializes in the room.": "Twoja nowa załoga pojawia się w pomieszczeniu",
    "Do something else instead.": "Zrób coś innego zamiast tego.",
    "DRONES OF THE DAY [33% OFF]": "PRZECENA DRONÓW [33% MNIEJ]",
    "Return.": "Powrót",
    "Boon Received": "Dar otrzymany",
    "Modular Missile Charger": "Modułowa Ładowarka pocisków ",
    "Mod. Charge": "Mod Ładowarka",
    "Chaotic Modular Missile Charger": "Chaotyczna Modułowa Ładowarka pocisków",
    "Mod. Chrg.\u2122": "Mod. Chrg.\u2122",
    "Modular Missile": "Modułowa Rakieta",
    "Mod. Missile": "Mod Rakieta",
    "Install the Lockdown Module.": "Zainstaluj moduł Zamrażający",
    "You activate the combat augment.": "Aktywujesz ulepszenie bojowe",
    "The crew is dead, leaving you with the ship. Its cargo is yours for the taking. Aboard is the special tech you expected, which you bring back to your ship.": "Załoga nie żyje, zostawiając Cię ze statkiem. Jego ładunek jest do twojej dyspozycji. Na pokładzie znajduje się specjalistyczny sprzęt, którego oczekiwałeś. Zabierasz go ze sobą na swój statek.",
    "We can't help.": "Nie możemy pomoc",
    "Ignore the ship.": "Ignoruj statek",
    "Ignore the station.": "Ignoruj stację",
    "(Jerry) \"Hello!\"": "(Jerry) \"Siema!\"",
    "Listen.": "Słuchaj",
    "Accept their offer.": "Zgódź się na ich ofertę",
    "Close your eyes and relax...": "Zamknij swoje oczy i się zrelaksuj",
    "(Mind Affecting Weapon) Induce chaos within the guard and slip past.": "(Broń oddziałująca na umysł) Wywołaj chaos wśród strażników i przemknij się obok nich.",
    "Ask for something else.": "Zapytaj o coś innego",
    "Get to Sector 5 with the Type A to unlock this ship.": "Dotrzyj do Sektora 5 Wersją A aby odblokować ten statek",
    "(Adv. Engines) Try to escape the Elite.": "(Zaawansowane silniki) Spróbuj uciec Elicie",
    "Attack them!": "Zaatakuj ich!",
    "Obyn": "Obyn",
    "You now have some time to do something on the ship.": "Masz teraz czas, by zrobić coś na statku",
    "Nevermind, let's fight!": "Nieważne, walczmy!",
    "You decide not to do anything and prepare to fight.": "Decydujesz by nie robić nic i ruszasz do walki",
    "Get to Sector 5 with the Type B or beat the game with the Type A to unlock this ship.": "Dotrzyj do Sektora 5 Wersją B aby odblokować ten statek",
    "Modular Beam": "Modułowy Promień",
    "Mod. Beam": "Mod Promień",
    "Leave them alone.": "Zostaw ich w spokoju",
    "Leave them be.": "Pozwól im żyć",
    "(Mind Control) Convince the guard to leave you alone.": "(Kontrola umysłu) Przekonaj strażnika, aby zostawił cię w spokoju.",
    "(Mind Control Weapon) Convince the guard to leave you alone.": "(Broń kontroli umysłu) Przekonaj strażnika, aby zostawił cię w spokoju."
}

mass_translate('locale/**/pl.po', REPLACE_MAP, overwrite=True)
